version: '3.8'

services:
  api:
    build: .
    container_name: bluetooth-scanner-api
    restart: unless-stopped
    ports:
      - "3210:3210"
    environment:
      - PORT=3210
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - default
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
